wk4d3/CookBook/config/routes.rb
CookBook::Application.routes.draw do

  resources :books do
    resources :recipes do
      resources :ingredients
    end
  end
end

wk4d3/CookBook/app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :title, :cuisine, :chef, :image
  
  has_many :recipes
end

wk4d3/CookBook/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :name, :measurement, :cost, :image

  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

wk4d3/CookBook/app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :name, :course, :cooktime, :servingsize, :instructions, :image, :book_id, :ingredient_ids

  belongs_to :book
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
end

wk4d3/CookBook/app/controllers/books_controller.rb
class BooksController < ApplicationController

	def index
 	 @books = Book.all
	end

	def new
    @book = Book.new
  end

  def create
    @book = Book.create(params[:book])
    render :show
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update_attributes(params[:book])
    render :show
  end

  def destroy
    book = Book.find(params[:id])
    book.delete
    redirect_to(books_path)
  end

end

wk4d3/CookBook/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end
  def new
    @recipe = Recipe.new
  end
  def create
    recipe = Recipe.create(params[:recipe])
    redirect_to(recipe)
  end
  def show
    @recipe = Recipe.find(params[:id])
  end
  def edit
    @recipe = Recipe.find(params[:id])
  end
  def update
    recipe = Recipe.find(params[:id])
    recipe.update_attributes(params[:recipe])
    redirect_to(recipe)
  end
  def destroy
    recipe = Recipe.find(params[:id])
    recipe.delete
    redirect_to(recipes_path)
  end
 end

wk4d3/CookBook/app/helpers/books_helper.rb
module BooksHelper
end

wk4d3/CookBook/app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <%= f.text_field :title, :autofocus => true %>
  <%= f.label :title %>
  <br>
  <%= f.text_field :cuisine %>
  <%= f.label :cuisine %>
  <br>
  <%= f.text_field :chef %>
  <%= f.label :chef %>
  <br>
  <%= f.text_field :image %>
  <%= f.label :image %>
  <br>
  <% Recipe.order(:name).each do |recipe| %>
    <span><%= recipe.name %></span>
    <%= check_box_tag 'book[recipe_ids][]', recipe.id, recipe.in?(@book.recipes.to_a) %>
  <% end %>
  <br>
  <%= f.submit %>
<% end %>

wk4d3/CookBook/app/views/books/edit.html.erb
<h1> Add New Book </h1>

<%= render partial: 'form' %>

wk4d3/CookBook/app/views/books/index.html.erb
<%= link_to('New Book', new_book_path) %>
<div class='spacer'></div>

<ol>
<% @books.each do |book| %>
  <li>
    <ul>
      <li><%= link_to(book.title, book) %></li>
      <li><%= book.cuisine %></li>
      <li><%= book.chef %></li>
      <li><%= image_tag(book.image) %></li>
    </ul>
  </li>
<% end %>
</ol>

wk4d3/CookBook/app/views/books/new.html.erb
<h1> Add New Book </h1>

<%= render partial: 'form' %>

wk4d3/CookBook/app/views/books/show.html.erb
<%= link_to('New Book', new_book_path) %>
:: <%= link_to('Edit Book', edit_book_path(@book)) %>
:: <%= link_to('Delete Book', @book, :method => :delete, :confirm => 'Are you sure?') %>
<div class='spacer'></div>

<ul>
  <li><%= link_to(@book.title, @book) %></li>
  <li><%= @book.cuisine %></li>
  <li><%= @book.chef %></li>
  <li><%= image_tag(@book.image) %></li>
</ul>

<div class='spacer'></div>

<ol>
<% @book.recipes.each do |recipe| %>
  <li>
    <ul>
      <li><%= recipe.name %></li>
      <li><%= image_tag(recipe.image) %></li>

      <% recipe.ingredients.each do |ingredient| %>
        <li><%= ingredient.name %></li>
        <li><%= image_tag(ingredient.image) %></li>
      <% end %>
    </ul>
  </li>
<% end %>
</ol>

wk4d3/CookBook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookBook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>