wk4d2/moma/config/routes.rb
R20130213MomaRails::Application.routes.draw do
  resources :artists, :paintings
end

wk4d2/moma/app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  nationality :string(255)
#  dob         :date
#  period      :string(255)
#  image       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Artist < ActiveRecord::Base
  attr_accessible :name, :nationality, :dob, :period, :image
  has_many :paintings
end

wk4d2/moma/app/models/painting.rb
# == Schema Information
#
# Table name: paintings
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  year       :string(255)
#  medium     :string(255)
#  style      :string(255)
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  artist_id  :integer
#

class Painting < ActiveRecord::Base
  attr_accessible :title, :year, :medium, :style, :image, :artist_id
  belongs_to :artist
end

wk4d2/moma/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.create(params[:artist])
    render :show #@artist
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update_attributes(params[:artist])
      render :show
    else
      render :edit 
    end
  end

  def destroy
    artist = Artist.find(params[:id])
    artist.delete
    redirect_to('/artists')
  end
end

wk4d2/moma/app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def index
    @paintings = Painting.all
  end
  def new
    @painting = Painting.new
  end
  def create
    painting = Painting.create(params[:painting])
    redirect_to(painting)
  end
  def show
    @painting = Painting.find(params[:id])
  end
  def edit
  end
  def update
  end
  def destroy
    painting = Painting.find(params[:id])
    painting.delete
    redirect_to(paintings_path)
  end
end

wk4d2/moma/app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
  <%= f.text_field :name %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :nationality %>
  <%= f.label :nationality %>
  <br>
  <%= f.text_field :dob %>
  <%= f.label :dob %>
  <br>
  <%= f.text_field :period %>
  <%= f.label :period %>
  <br>
  <%= f.text_field :image %>
  <%= f.label :image %>
  <br>
  <%= f.submit %>
<% end %>

wk4d2/moma/app/views/artists/edit.html.erb
<h1>Edit Artist</h1>
<%= render :partial => 'form' %>

wk4d2/moma/app/views/artists/index.html.erb
<ol>
<% @artists.each do |artist| %>
  <li>
    <ul>
      <li><%= link_to artist.name, artist %></li>
      <li><%= artist.nationality %></li>
      <li><%= artist.dob.strftime('%B %d, %Y') %></li>
      <li><%= artist.period %></li>
      <li><%= image_tag(artist.image) %></li>
    </ul>
  </li>
<% end %>
</ol>

wk4d2/moma/app/views/artists/new.html.erb
<h1>New Artist</h1>
<%= render :partial => 'form' %>

wk4d2/moma/app/views/artists/show.html.erb
<ul>
  <li><%= link_to @artist.name, @artist %></li>
  <li><%= @artist.nationality %></li>
  <li><%= @artist.dob.strftime('%B %d, %Y') %></li>
  <li><%= @artist.period %></li>
  <li><%= image_tag(@artist.image) %></li>
</ul>

<% @artist.paintings.each do |painting| %>
  <ul>
    <li><%= link_to painting.title, painting %></li>
    <li><%= painting.year %></li>
    <li><%= painting.medium %></li>
    <li><%= painting.style %></li>
    <li><%= image_tag(painting.image) %></li>
  </ul>
<% end %>

<%= button_to 'Delete', @artist, :method => :delete %>
<%= link_to 'Edit', edit_artist_path(@artist) %>

wk4d2/moma/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>R20130213MomaRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <ul>
      <li><%= link_to('Artists', artists_path) %></li>
      <li><%= link_to('Paintings', paintings_path) %></li>
      <li><%= link_to('(New Artist)', new_artist_path) %></li>
      <li><%= link_to('(New Painting)', new_painting_path) %></li>
    </ul>
  </nav>

  <section class='clear'><%= yield %></section>

</body>
</html>

wk4d2/moma/app/views/paintings/index.html.erb
<ol>
<% @paintings.each do |painting| %>
  <li>
    <ul>
      <li><%= link_to painting.title, painting %></li>
      <li><%= painting.year %></li>
      <li><%= painting.medium %></li>
      <li><%= painting.style %></li>
      <li><%= image_tag(painting.image) %></li>
    </ul>
  </li>
<% end %>
</ol>

wk4d2/moma/app/views/paintings/new.html.erb
<%= form_for @painting do |f| %>
  <%= f.label :artist_id %>
  <%= f.select :artist_id, Artist.all.map{|artist| [artist.name, artist.id]}, :include_blank => true, :prompt => "Pick Artist!" %>
  <br>
  <%= f.text_field :title %>
  <%= f.label :title %>
  <br>
  <%= f.text_field :year %>
  <%= f.label :year %>
  <br>
  <%= f.text_field :medium %>
  <%= f.label :medium %>
  <br>
  <%= f.text_field :style %>
  <%= f.label :style %>
  <br>
  <%= f.text_field :image %>
  <%= f.label :image %>
  <br>
  <%= f.submit %>
<% end %>

wk4d2/moma/app/views/paintings/show.html.erb
<ul>
  <li><%= link_to @painting.title, @painting %></li>
  <li><%= @painting.year %></li>
  <li><%= @painting.medium %></li>
  <li><%= @painting.style %></li>
  <li><%= image_tag(@painting.image) %></li>
</ul>

<%= link_to 'Delete', @painting, :method => :delete, :confirm => 'Is it ok to delete?' %>