wk5d4/asset_project/config/routes.rb
AssetProject::Application.routes.draw do
  resources :outfits

  

end

wk5d4/asset_project/app/models/outfit.rb
class Outfit < ActiveRecord::Base
	validates_presence_of :name
end

wk5d4/asset_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

wk5d4/asset_project/app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  before_action :set_outfit, only: [:show, :edit, :update, :destroy]

  # GET /outfits
  # GET /outfits.json
  def index
    @outfits = Outfit.all
  end

  # GET /outfits/1
  # GET /outfits/1.json
  def show
  end

  # GET /outfits/new
  def new
    @outfit = Outfit.new(user_id: current_user.id)
  end

  # GET /outfits/1/edit
  def edit
  end

  # POST /outfits
  # POST /outfits.json
  def create
    @outfit = Outfit.new(outfit_params)

    respond_to do |format|
      if @outfit.save
        format.html { redirect_to @outfit, notice: 'Outfit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @outfit }
      else
        format.html { render action: 'new' }
        format.json { render json: @outfit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outfits/1
  # PATCH/PUT /outfits/1.json
  def update
    respond_to do |format|
      if @outfit.update(outfit_params)
        format.html { redirect_to @outfit, notice: 'Outfit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @outfit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outfits/1
  # DELETE /outfits/1.json
  def destroy
    @outfit.destroy
    respond_to do |format|
      format.html { redirect_to outfits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outfit
      @outfit = Outfit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outfit_params
      params[:outfit]
    end
end

wk5d4/asset_project/app/helpers/application_helper.rb
module ApplicationHelper
end

wk5d4/asset_project/app/helpers/outfits_helper.rb
module OutfitsHelper
end

wk5d4/asset_project/app/views/outfits/_form.html.erb
<%= form_for(@outfit) do |f| %>
  <% if @outfit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outfit.errors.count, "error") %> prohibited this outfit from being saved:</h2>

      <ul>
      <% @outfit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

wk5d4/asset_project/app/views/outfits/edit.html.erb
<h1>Editing outfit</h1>

<%= render 'form' %>

<%= link_to 'Show', @outfit %> |
<%= link_to 'Back', outfits_path %>

wk5d4/asset_project/app/views/outfits/index.html.erb
<h1>Listing outfits</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @outfits.each do |outfit| %>
      <tr>
        <td><%= link_to 'Show', outfit %></td>
        <td><%= link_to 'Edit', edit_outfit_path(outfit) %></td>
        <td><%= link_to 'Destroy', outfit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Outfit', new_outfit_path %>

wk5d4/asset_project/app/views/outfits/new.html.erb
<h1>New outfit</h1>

<%= render 'form' %>

<%= link_to 'Back', outfits_path %>

wk5d4/asset_project/app/views/outfits/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_outfit_path(@outfit) %> |
<%= link_to 'Back', outfits_path %>